### ISSUE TITLE
请问有个具体的例子么

### ISSUE THREAD

**Issue by likohank** [yeefire/cloud-class-replay#1]
通过抓包 获取到的 网址 
`https://1258712167.vod2.myqcloud.com/25121a6avodtransbj1258712167/1e5f63b85285890804492825776/drm/voddrm.token.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXTg2ZGE2OWE3YzhmZTU5NzBlNmYxNDA1YWJjN2ZjMjNjMWIzZDY3NjkxYTY1OGUzNDg4NjFlNGQzYTY5OTRmMmEzMDVhM2JhMzRjZWIzNGJjODQzODY5MmQ0ZTQ2ZjA0NDE3N2E0ZWRiMzdhMzFjMjRkNmY5NzI3ZjFlNjc4ZjU0YzBmMTNmOTYyYzA3YmViYg==.v.f30739.m3u8?exper=0&sign=681701c9daf8119d87ac5bbd689c4c11&t=601a82e8&us=1476414304413178497`

放在参数2 ， 进行 `playlist = m3u8.load(m3u8_file_uri, verify_ssl=False)` 返回的列表总是空

**Comment by likohank** [comment]
嗯。。。。。如上 URL  Py里 写死就能用了。  看来是 作为参数时 的问题，虽然加了 双引号。

**Comment by yeefire** [comment]
> 嗯。。。。。如上 URL Py里 写死就能用了。 看来是 作为参数时 的问题，虽然加了 双引号。

不清楚您那边的环境，我这边的话用 macOS Iterm2 终端的zsh 可以正常传递参数。😊

**Comment by yeefire** [comment]
> 嗯。。。。。如上 URL Py里 写死就能用了。 看来是 作为参数时 的问题，虽然加了 双引号。

shell> python3 tencent_class_m3u8.py <课程保存名称> <课程m3u8>

**Comment by likohank** [comment]
> > 嗯。。。。。如上 URL Py里 写死就能用了。 看来是 作为参数时 的问题，虽然加了 双引号。
> 
> shell> python3 tencent_class_m3u8.py <课程保存名称> <课程m3u8>

应该是我本地Windows Pycharm 的问题， 谢谢Owner。
